name: Scrape Stream URL

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          cd scraper
          npm install

      - name: Run Scraper
        run: |
          cd scraper
          npm start

      - name: Commit and Push .json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          cp scraper/stream.json stream.json
          git add stream.json
          git commit -m "Update stream URL [auto]" || echo "No changes"
          git push